//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 11:22:05 AM CET 
//


package com.ericsson.configmaster.paramconfig.autogen;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.configmaster.paramconfig.autogen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.configmaster.paramconfig.autogen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParamConfig }
     * 
     */
    public ParamConfig createParamConfig() {
        return new ParamConfig();
    }

    /**
     * Create an instance of {@link ParamConfig.EventAddition }
     * 
     */
    public ParamConfig.EventAddition createParamConfigEventAddition() {
        return new ParamConfig.EventAddition();
    }

    /**
     * Create an instance of {@link ParamConfig.Enrichment }
     * 
     */
    public ParamConfig.Enrichment createParamConfigEnrichment() {
        return new ParamConfig.Enrichment();
    }

    /**
     * Create an instance of {@link ParamConfig.Enrichment.EventToEnrich }
     * 
     */
    public ParamConfig.Enrichment.EventToEnrich createParamConfigEnrichmentEventToEnrich() {
        return new ParamConfig.Enrichment.EventToEnrich();
    }

    /**
     * Create an instance of {@link ParamConfig.Analysis }
     * 
     */
    public ParamConfig.Analysis createParamConfigAnalysis() {
        return new ParamConfig.Analysis();
    }

    /**
     * Create an instance of {@link ParamConfig.Analysis.EventToAnalyze }
     * 
     */
    public ParamConfig.Analysis.EventToAnalyze createParamConfigAnalysisEventToAnalyze() {
        return new ParamConfig.Analysis.EventToAnalyze();
    }

    /**
     * Create an instance of {@link ParamConfig.EventAddition.EventToAdd }
     * 
     */
    public ParamConfig.EventAddition.EventToAdd createParamConfigEventAdditionEventToAdd() {
        return new ParamConfig.EventAddition.EventToAdd();
    }

    /**
     * Create an instance of {@link ParamConfig.Enrichment.EventToEnrich.ParamToEnrich }
     * 
     */
    public ParamConfig.Enrichment.EventToEnrich.ParamToEnrich createParamConfigEnrichmentEventToEnrichParamToEnrich() {
        return new ParamConfig.Enrichment.EventToEnrich.ParamToEnrich();
    }

    /**
     * Create an instance of {@link ParamConfig.Analysis.EventToAnalyze.ParamToAnalyze }
     * 
     */
    public ParamConfig.Analysis.EventToAnalyze.ParamToAnalyze createParamConfigAnalysisEventToAnalyzeParamToAnalyze() {
        return new ParamConfig.Analysis.EventToAnalyze.ParamToAnalyze();
    }

}
