/*------------------------------------------------------------------------------
 ******************************************************************************
 * (c) Ericsson Inc. 2018 - All rights reserved.
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 ******************************************************************************
 *----------------------------------------------------------------------------*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.07.11 at 03:24:54 PM CEST
//

package com.ericsson.configmaster.appconfig.autogen;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSource" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GeneralInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="UniqueIDType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DefaultRelease" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DefaultEventID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="FileNamePattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ComplexParameters">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Parameter" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Component" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="startBit" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="lengthBits" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="defaultComponentId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmlns:xsi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xsi:noNamespaceSchemaLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "dataSource" })
@XmlRootElement(name = "AppConfiguration")
public class AppConfiguration {

    @XmlElement(name = "DataSource", required = true)
    protected List<AppConfiguration.DataSource> dataSource;
    @XmlAttribute(name = "xmlns:xsi")
    protected String xmlnsXsi;
    @XmlAttribute(name = "xsi:noNamespaceSchemaLocation")
    protected String xsiNoNamespaceSchemaLocation;

    /**
     * Gets the value of the dataSource property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the dataSource property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDataSource().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link AppConfiguration.DataSource }
     */
    public List<AppConfiguration.DataSource> getDataSource(){
        if(dataSource == null){
            dataSource = new ArrayList<AppConfiguration.DataSource>();
        }
        return this.dataSource;
    }

    /**
     * Gets the value of the xmlnsXsi property.
     *
     * @return possible object is {@link String }
     */
    public String getXmlnsXsi(){
        return xmlnsXsi;
    }

    /**
     * Sets the value of the xmlnsXsi property.
     *
     * @param value
     *            allowed object is {@link String }
     */
    public void setXmlnsXsi(String value){
        this.xmlnsXsi = value;
    }

    /**
     * Gets the value of the xsiNoNamespaceSchemaLocation property.
     *
     * @return possible object is {@link String }
     */
    public String getXsiNoNamespaceSchemaLocation(){
        return xsiNoNamespaceSchemaLocation;
    }

    /**
     * Sets the value of the xsiNoNamespaceSchemaLocation property.
     *
     * @param value
     *            allowed object is {@link String }
     */
    public void setXsiNoNamespaceSchemaLocation(String value){
        this.xsiNoNamespaceSchemaLocation = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GeneralInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="UniqueIDType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DefaultRelease" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DefaultEventID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FileNamePattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ComplexParameters">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Parameter" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Component" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="startBit" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="lengthBits" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="defaultComponentId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "generalInfo", "fileNamePattern", "uniqueId", "complexParameters" })
    public static class DataSource {

        @XmlElement(name = "GeneralInfo", required = true)
        protected AppConfiguration.DataSource.GeneralInfo generalInfo;
        @XmlElement(name = "FileNamePattern", required = true)
        protected String fileNamePattern;
        @XmlElement(name = "UniqueId", required = true)
        protected String uniqueId;
        @XmlElement(name = "ComplexParameters", required = true)
        protected AppConfiguration.DataSource.ComplexParameters complexParameters;
        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the generalInfo property.
         *
         * @return possible object is {@link AppConfiguration.DataSource.GeneralInfo }
         */
        public AppConfiguration.DataSource.GeneralInfo getGeneralInfo(){
            return generalInfo;
        }

        /**
         * Sets the value of the generalInfo property.
         *
         * @param value
         *            allowed object is {@link AppConfiguration.DataSource.GeneralInfo }
         */
        public void setGeneralInfo(AppConfiguration.DataSource.GeneralInfo value){
            this.generalInfo = value;
        }

        /**
         * Gets the value of the fileNamePattern property.
         *
         * @return possible object is {@link String }
         */
        public String getFileNamePattern(){
            return fileNamePattern;
        }

        /**
         * Sets the value of the fileNamePattern property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setFileNamePattern(String value){
            this.fileNamePattern = value;
        }

        /**
         * Gets the value of the uniqueId property.
         *
         * @return possible object is {@link String }
         */
        public String getUniqueId(){
            return uniqueId;
        }

        /**
         * Sets the value of the uniqueId property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setUniqueId(String value){
            this.uniqueId = value;
        }

        /**
         * Gets the value of the complexParameters property.
         *
         * @return possible object is {@link AppConfiguration.DataSource.ComplexParameters }
         */
        public AppConfiguration.DataSource.ComplexParameters getComplexParameters(){
            return complexParameters;
        }

        /**
         * Sets the value of the complexParameters property.
         *
         * @param value
         *            allowed object is {@link AppConfiguration.DataSource.ComplexParameters }
         */
        public void setComplexParameters(AppConfiguration.DataSource.ComplexParameters value){
            this.complexParameters = value;
        }

        /**
         * Gets the value of the value property.
         *
         * @return possible object is {@link String }
         */
        public String getValue(){
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value
         *            allowed object is {@link String }
         */
        public void setValue(String value){
            this.value = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Parameter" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Component" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="startBit" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="lengthBits" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="defaultComponentId" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "parameter" })
        public static class ComplexParameters {

            @XmlElement(name = "Parameter", required = true)
            protected List<AppConfiguration.DataSource.ComplexParameters.Parameter> parameter;

            /**
             * Gets the value of the parameter property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
             * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the parameter property.
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getParameter().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link AppConfiguration.DataSource.ComplexParameters.Parameter }
             */
            public List<AppConfiguration.DataSource.ComplexParameters.Parameter> getParameter(){
                if(parameter == null){
                    parameter = new ArrayList<AppConfiguration.DataSource.ComplexParameters.Parameter>();
                }
                return this.parameter;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Component" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="startBit" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="lengthBits" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="defaultComponentId" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "component" })
            public static class Parameter {

                @XmlElement(name = "Component", required = true)
                protected List<AppConfiguration.DataSource.ComplexParameters.Parameter.Component> component;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "defaultComponentId")
                protected Integer defaultComponentId;

                /**
                 * Gets the value of the component property.
                 * <p>
                 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list
                 * will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the component property.
                 * <p>
                 * For example, to add a new item, do as follows:
                 * 
                 * <pre>
                 * getComponent().add(newItem);
                 * </pre>
                 * <p>
                 * Objects of the following type(s) are allowed in the list {@link AppConfiguration.DataSource.ComplexParameters.Parameter.Component }
                 */
                public List<AppConfiguration.DataSource.ComplexParameters.Parameter.Component> getComponent(){
                    if(component == null){
                        component = new ArrayList<AppConfiguration.DataSource.ComplexParameters.Parameter.Component>();
                    }
                    return this.component;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getName(){
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value
                 *            allowed object is {@link String }
                 */
                public void setName(String value){
                    this.name = value;
                }

                /**
                 * Gets the value of the defaultComponentId property.
                 *
                 * @return possible object is {@link Integer }
                 */
                public Integer getDefaultComponentId(){
                    return defaultComponentId;
                }

                /**
                 * Sets the value of the defaultComponentId property.
                 *
                 * @param value
                 *            allowed object is {@link Integer }
                 */
                public void setDefaultComponentId(Integer value){
                    this.defaultComponentId = value;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 * <p>
                 * The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="startBit" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="lengthBits" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Component {

                    @XmlAttribute(name = "Id")
                    protected Integer id;
                    @XmlAttribute(name = "startBit")
                    protected Integer startBit;
                    @XmlAttribute(name = "lengthBits")
                    protected Integer lengthBits;
                    @XmlAttribute(name = "comment")
                    protected String comment;

                    /**
                     * Gets the value of the id property.
                     *
                     * @return possible object is {@link Integer }
                     */
                    public Integer getId(){
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     *
                     * @param value
                     *            allowed object is {@link Integer }
                     */
                    public void setId(Integer value){
                        this.id = value;
                    }

                    /**
                     * Gets the value of the startBit property.
                     *
                     * @return possible object is {@link Integer }
                     */
                    public Integer getStartBit(){
                        return startBit;
                    }

                    /**
                     * Sets the value of the startBit property.
                     *
                     * @param value
                     *            allowed object is {@link Integer }
                     */
                    public void setStartBit(Integer value){
                        this.startBit = value;
                    }

                    /**
                     * Gets the value of the lengthBits property.
                     *
                     * @return possible object is {@link Integer }
                     */
                    public Integer getLengthBits(){
                        return lengthBits;
                    }

                    /**
                     * Sets the value of the lengthBits property.
                     *
                     * @param value
                     *            allowed object is {@link Integer }
                     */
                    public void setLengthBits(Integer value){
                        this.lengthBits = value;
                    }

                    /**
                     * Gets the value of the comment property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getComment(){
                        return comment;
                    }

                    /**
                     * Sets the value of the comment property.
                     *
                     * @param value
                     *            allowed object is {@link String }
                     */
                    public void setComment(String value){
                        this.comment = value;
                    }

                }

            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="UniqueIDType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DefaultRelease" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DefaultEventID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "uniqueIDType", "defaultRelease", "defaultEventID" })
        public static class GeneralInfo {

            @XmlElement(name = "UniqueIDType", required = true)
            protected String uniqueIDType;
            @XmlElement(name = "DefaultRelease", required = true)
            protected String defaultRelease;
            @XmlElement(name = "DefaultEventID")
            protected int defaultEventID;

            /**
             * Gets the value of the uniqueIDType property.
             *
             * @return possible object is {@link String }
             */
            public String getUniqueIDType(){
                return uniqueIDType;
            }

            /**
             * Sets the value of the uniqueIDType property.
             *
             * @param value
             *            allowed object is {@link String }
             */
            public void setUniqueIDType(String value){
                this.uniqueIDType = value;
            }

            /**
             * Gets the value of the defaultRelease property.
             *
             * @return possible object is {@link String }
             */
            public String getDefaultRelease(){
                return defaultRelease;
            }

            /**
             * Sets the value of the defaultRelease property.
             *
             * @param value
             *            allowed object is {@link String }
             */
            public void setDefaultRelease(String value){
                this.defaultRelease = value;
            }

            /**
             * Gets the value of the defaultEventID property.
             */
            public int getDefaultEventID(){
                return defaultEventID;
            }

            /**
             * Sets the value of the defaultEventID property.
             */
            public void setDefaultEventID(int value){
                this.defaultEventID = value;
            }

        }

    }

}
